### ISSUE TITLE
Please parse csv files

### ISSUE THREAD

**Issue by jrhillae** [jrhillae/GRIIS#1]
@jhpoelen: Hi, I would like to align the scientificName in my semicolon separated csv file:

id | taxonID | scientificName | acceptedNameUsage | kingdom | phylum | class | order | family | taxonRank | taxonomicStatus
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
86500 | 86500 | Acanthoscelides obtectus (Say, 1831) |   | Animalia | Arthropoda | Insecta | Coleoptera | Chrysomelidae | SPECIES | ACCEPTED

**Comment by jhpoelen** [comment]
Hey @jrhillae @qgroom et al.

Thanks for taking the time to share your ideas today during the Alien CSI hack-a-thon in Romania. 

I've attempted to update the review script to:

1. accept txt and csv file.
2. select text in column name "scientificName"
3. upload a zip file with name full name review results
4. parse name before attempt to resolve them against known taxonomies
5. fail name alignment on when no names could be found

Please let me know if this addresses your concerns. You should be able to re-run the alignment actions in Github. Alternatively, you can trigger another alignment by making a change (any change) in your repository.

Please close this issue if you feel your needs are met. If not, please provide comments.

**Comment by jhpoelen** [comment]
Examples of recent reviews:

1. fail on no names - https://github.com/jhpoelen/GRIIS/runs/5484777634?check_suite_focus=true#step:5:36 - ```no names found: please check your configuration Error: Process completed with exit code 1.```
2. matching csv txt files -  https://github.com/jhpoelen/GRIIS/runs/5484563420?check_suite_focus=true#step:5:146 ```[jhpoelen/GRIIS] has 700 names alignment note(s)```

**Comment by jrhillae** [comment]
@jhpoelen and @qgroom: Thank you for developing this tool, it is very useful! The output of my run is here: https://github.com/jrhillae/GRIIS/runs/5491969584?check_suite_focus=true. There is an error but I do not know exactly why. Is it a warning that not all names could be aligned? Can I ignore that?

Maybe we can just go over the output later today (for you in the morning ;) )? The column ResolvedName is the most important column for me to proceed with? It is the original list of species (without authorship) and all possible synonymes?

Thank you for your help.

**Comment by jhpoelen** [comment]
@jrhillae Thanks for having a peek at the output of the name alignment run. I would very much like to review the results with you and figure ways to make the output more useful for you. Perhaps after our review you can suggest an alternate way to present the information contained in the current report, and then I can try to realize your suggestion. 

The form would be:

Currently, the reports shows:
```
Name Alignment By Nomer
[...]
```

Instead, I'd like the report to show:
```
Name Alignment by Jasmijn
[...]
```

Thank for your patience in looking at these cryptic messages in funky text/log files. 

I am hoping to join today at the usual time.

**Comment by jrhillae** [comment]
@jhpoelen : I am available now and in the meeting of the hackaton :).

**Comment by jhpoelen** [comment]
joining . . .

**Comment by jhpoelen** [comment]
@jrhillae please close this issue if you believe that your csv is read / reviewed ok.
